apiVersion: v2
name: financeapp
description: Top chart for financeapp

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"
dependencies:
  - name: account-service
    version: "0.1.2"
    repository: "file://charts/account-service"
  - name: audit-service
    version: "0.1.2"
    repository: "file://charts/audit-service"
  - name: cash-service
    version: "0.1.2"
    repository: "file://charts/cash-service"
  - name: dictionaries-service
    version: "0.1.2"
    repository: "file://charts/dictionaries-service"
  - name: exchange-service
    version: "0.1.2"
    repository: "file://charts/exchange-service"
  - name: front-ui
    version: "0.1.2"
    repository: "file://charts/front-ui"
  - name: notification-service
    version: "0.1.2"
    repository: "file://charts/notification-service"
  - name: transfer-service
    version: "0.1.2"
    repository: "file://charts/transfer-service"
  - name: postgresql
    version: "14.2.3"
    repository: "file://charts/postgresql-14.2.3"
  - name: keycloak
    repository: "file://charts/keycloak-24.7.3"
    version: "24.7.3"
    alias: keycloak
    condition: keycloak.enabled
  - name: kafka
    version: "27.1.2"
    repository: "file://charts/kafka-27.1.2"
    alias: kafka
    condition: kafka.enabled
  - name: zipkin
    version: "1.3.10"
    repository: "file://charts/zipkin-1.3.10"
    alias: zipkin
    condition: zipkin.enabled
#  - name: kube-prometheus
#    version: "11.2.6"
#    repository: "file://charts/kube-prometheus-11.2.6"
  - name: prometheus
    version: "27.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "8.5.12"
    repository: https://grafana.github.io/helm-charts
  - name: logstash
    version: "7.17.3"
    repository: https://helm.elastic.co
    condition: logstash.enabled
  - name: elasticsearch
    version: "8.5.1"
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: kibana
    version: "10.2.8"
    repository: "file://charts/kibana-10.2.8"
    condition: kibana.enabled