apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        health {
           lameduck 5s
        }
        rewrite name keycloak.local financeapp-keycloak.test.svc.cluster.local
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-07-22T13:28:12Z","name":"coredns","namespace":"kube-system","resourceVersion":"194188","uid":"bcf77342-5161-4a5a-a26c-9503e72c2724"}}
  creationTimestamp: "2025-07-22T13:28:12Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "198004"
  uid: bcf77342-5161-4a5a-a26c-9503e72c2724
