spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
            user-name-attribute: preferred_username
        registration:
          zbankapi:
            provider: keycloak
            client-id: zbankapi
            client-secret: yBxbVdRbMIgOHjEhDaV8aTp8pYl1UXe1
            authorization-grant-type: client_credentials
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
          user-name-attribute: preferred_username
  cloud:
    openfeign:
      oauth2:
        clientRegistrationId: zbankapi
        enabled: true
  datasource:
    init: never
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schema: ${SPRING_DATASOURCE_EXCHANGE_SCHEMA}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: ${SPRING_DATASOURCE_URL}
    enabled: true
    default-schema: ${SPRING_DATASOURCE_EXCHANGE_SCHEMA}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
exceptions:
  insufficientFundsFailure: ${INSUFFICENT_FUNDS_FAILURE:"Insufficient funds"}
  currencyNotFoundFailure: ${CURRENCY_NOT_FOUND_FAILURE:"Currency info not found"}
  accNotFoundFailure: ${ACC_NOT_FOUND_FAILURE:"Password is not updated"}