spring:
  application:
    name: exchange-service
  profiles:
    active: dev
  jpa:
#    database-platform: org.hibernate.dialect.PostgresSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: none
  datasource:
    init: never
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env, prometheus 
  security:
    enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
server:
  port: ${EXCHANGE_SERVER_PORT:8085}