apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "exchange-service.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.exchange-service.serviceAccount.name | default (include "exchange-service.serviceAccountName" .) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "exchange-service.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io