spring:
  config:
    import: optional:consul:consul:8500
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
            user-name-attribute: preferred_username
        registration:
          zbankapi:
            provider: keycloak
            client-id: zbankapi
            client-secret: yBxbVdRbMIgOHjEhDaV8aTp8pYl1UXe1
            authorization-grant-type: client_credentials
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
          user-name-attribute: preferred_username
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        metadata:
          addLabels: true
          addAnnotations: true
    openfeign:
      oauth2:
        clientRegistrationId: zbankapi
        enabled: true
  datasource:
    init: never
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schema: ${SPRING_DATASOURCE_AUDIT_SCHEMA}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: ${SPRING_DATASOURCE_URL}
    enabled: true
    default-schema: ${SPRING_DATASOURCE_AUDIT_SCHEMA}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
exceptions:
  deserFailure: ${EXCEPTIONS_DESER_FAILURE:Cannot deserialize payload}
  operationFailure: ${EXCEPTIONS_OPERATION_FAILURE:Operation type not recognized}