{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Панель оповещений", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Среднее время обновления валют за 5 мин",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(financeapp_currency_duration_seconds_sum[5m])\n/\nrate(financeapp_currency_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Некорректный аудит по пользователям за 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (login) (increase(financeapp_failed_audit_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ошибочных переводов по пользователям",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (userId) (financeapp_failed_transfers_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}