CREATE SCHEMA IF NOT EXISTS account_info;
CREATE SCHEMA IF NOT EXISTS cash_info;
CREATE SCHEMA IF NOT EXISTS exchange_info;
CREATE SCHEMA IF NOT EXISTS rule_info;
CREATE SCHEMA IF NOT EXISTS transfer_info;
CREATE SCHEMA IF NOT EXISTS notificatilon_info;