apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-db
  labels:
    app.kubernetes.io/name: db-credentials
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | quote }}