spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mynet:7080/realms/zbank
          user-name-attribute: preferred_username
  application:
    name: gateway-service
  config:
    import: optional:consul:consul:8500 # импорт конфигурации из consul
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: yaml
    gateway:
      routes:
        - id: to-account-service
          uri: http://account-service:8081/
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account(?<segment>.*), /api/account\${segment}
            - TokenRelay
        - id: to-cash-service
          uri: http://cash-service:8084/
          predicates:
            - Path=/cash/**
          filters:
            - RewritePath=/cash(?<segment>.*), /api/cash\${segment}
            - TokenRelay
        - id: to-exchange-service
          uri: http://exchange-service:8085/
          predicates:
            - Path=/exchange/**
          filters:
            - RewritePath=/exchange(?<segment>.*), /api/exchange\${segment}
            - TokenRelay
        - id: to-transfer-service
          uri: http://transfer-service:8086/
          predicates:
            - Path=/transfer/**
          filters:
            - RewritePath=/transfer(?<segment>.*), /api/transfer\${segment}
            - TokenRelay
        - id: to-user-service
          uri: http://account-service:8081/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>.*), /api/user$\{segment}
            - TokenRelay
        - id: to-dictionaries-service
          uri: http://dictionaries-service:8083/
          predicates:
            - Path=/dictionary/**
          filters:
            - RewritePath=/dictionary(?<segment>.*), /api/dictionary$\{segment}
            - TokenRelay
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG