spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mynet:7080/realms/zbank
          user-name-attribute: preferred_username
#      client:
#        provider:
#          keycloak:
#            authorization-uri: http://localhost:7080/realms/zbank/protocol/openid-connect/auth
#            token-uri: http://keycloak:8080/realms/zbank/protocol/openid-connect/token
#            user-info-uri: http://keycloak:8080/realms/zbank/protocol/openid-connect/userinfo
#            jwk-set-uri: http://keycloak:8080/realms/zbank/protocol/openid-connect/certs
#            user-name-attribute: preferred_username
        #            authorization-uri: http://localhost:7080/realms/zbank/protocol/openid-connect/auth
        #            issuer-uri: http://keycloak:8080/realms/zbank
#        registration:
#          gateway-client:
#            provider: keycloak
#            client-id: zbankapp
#            client-secret: g3WnFjX9r8zxmhlY7yILHV5hZ3RtLUjw
#            authorization-grant-type: client_credentials
#            scope: openid, profile, email
  application:
    name: gateway-service
  config:
    import: optional:consul:consul:8500 # импорт конфигурации из consul
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: yaml
    gateway:
      routes:
        - id: to-account-service
          uri: http://account-service:8081/
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account(?<segment>.*), /api/account\${segment}
            - TokenRelay
        - id: to-user-service
          uri: http://account-service:8081/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>.*), /api/user$\{segment}
            - TokenRelay
        - id: to-dictionaries-service
          uri: http://dictionaries-service:8081/
          predicates:
            - Path=/dictionary/**
          filters:
            - RewritePath=/dictionary(?<segment>.*), /api/dictionary$\{segment}
            - TokenRelay
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG