spring:
  application:
    name: gateway-service
  profiles:
    active: dev
server:
  port: ${GATEWAY_SERVICE_PORT:8082}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env
  security:
    enabled: true
  endpoint:
    health:
      show-details: always
