spring:
  application:
    name: frontui
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env
  security:
    enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    org.springframework.security: DEBUG