spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        metadata:
          addLabels: true
          addAnnotations: true
    openfeign:
      oauth2:
        clientRegistrationId: zbankapi
        enabled: true
      circuitbreaker:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak-browser:
            authorization-uri: http://keycloak.local/realms/zbank/protocol/openid-connect/auth
            token-uri: http://financeapp-keycloak.test.svc.cluster.local:8080/realms/zbank/protocol/openid-connect/token
            user-info-uri: http://financeapp-keycloak.test.svc.cluster.local:8080/realms/zbank/protocol/openid-connect/userinfo
            jwk-set-uri: http://financeapp-keycloak.test.svc.cluster.local:8080/zbank/protocol/openid-connect/certs
            logout-uri: http://keycloak.local/realms/zbank/protocol/openid-connect/logout
            user-name-attribute: preferred_username
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak-browser
            client-id: zbankapp
            client-secret: g3WnFjX9r8zxmhlY7yILHV5hZ3RtLUjw
            client-name: zbankapp
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
          zbankapi:
            provider: keycloak
            client-id: zbankapi
            client-secret: yBxbVdRbMIgOHjEhDaV8aTp8pYl1UXe1
            authorization-grant-type: client_credentials
            scope: openid
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
    instances:
      account-client:
        baseConfig: default
      dictionary-client:
        baseConfig: default
      notification-client:
        baseConfig: default
      user-client:
        baseConfig: default
      cash-client:
        baseConfig: default
      exchange-client:
        baseConfig: default
      transfer-client:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      account-client:
        baseConfig: default
      dictionary-client:
        baseConfig: default
      notification-client:
        baseConfig: default
      user-client:
        baseConfig: default
      cash-client:
        baseConfig: default
      exchange-client:
        baseConfig: default
      transfer-client:
        baseConfig: default
logging:
  level:
    feign: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
    io.github.resilience4j: DEBUG
    net.microfin.financeapp.client: DEBUG
client:
  service:
    account: ${spring.release.name:financeapp}-account-service
    audit: ${spring.release.name:financeapp}-audit-service
    cash: ${spring.release.name:financeapp}-cash-service
    dictionaries: ${spring.release.name:financeapp}-dictionaries-service
    exchange: ${spring.release.name:financeapp}-exchange-service
    notification: ${spring.release.name:financeapp}-notification-service
    transfer: ${spring.release.name:financeapp}-transfer-service
