spring:
  application:
    name: frontui
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    org.springframework.security: DEBUG