apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cash-service.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ index .Values "cash-service" "serviceAccount" "name" | default (include "cash-service.serviceAccountName" .) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "cash-service.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io