spring:
  config:
    import: optional:consul:consul:8500
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://mynet:7080/realms/zbank
            user-name-attribute: preferred_username
        registration:
          zbankapi:
            provider: keycloak
            client-id: zbankapi
            client-secret: yBxbVdRbMIgOHjEhDaV8aTp8pYl1UXe1
            authorization-grant-type: client_credentials
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://mynet:7080/realms/zbank
          user-name-attribute: preferred_username
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: yaml
  liquibase:
    enabled: false