spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schema: ${SPRING_DATASOURCE_SCHEMA}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    rollback-file: classpath:/db/changelog/roll-back-file