spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
  kafka:
    producer:
      acks: all
      retries: 5
      delivery-timeout-ms: 120000
      bootstrap-servers: ${KAFKA_URL:financeapp-kafka:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
            user-name-attribute: preferred_username
        registration:
          zbankapi:
            provider: keycloak
            client-id: zbankapi
            client-secret: yBxbVdRbMIgOHjEhDaV8aTp8pYl1UXe1
            authorization-grant-type: client_credentials
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
          user-name-attribute: preferred_username
  liquibase:
    enabled: false
scheduler:
  enabled: ${SCHEDULER_ENABLED:true}