spring:
  application:
    name: dictionaries-service
  profiles:
    active: dev
server:
  port: ${SERVER_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env