spring:
  application:
    name: dictionaries-service
  profiles:
    active: dev
server:
  port: ${DICTIONARIES_SERVER_PORT:8083}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env