spring:
  config:
    import: optional:consul:consul:8500
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://mynet:7080/realms/zbank
            user-name-attribute: preferred_username
        registration:
          zbankapi:
            provider: keycloak
            client-id: zbankapi
            client-secret: yBxbVdRbMIgOHjEhDaV8aTp8pYl1UXe1
            authorization-grant-type: client_credentials
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://mynet:7080/realms/zbank
          user-name-attribute: preferred_username
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        prefix: config
        defaultContext: account-service
        format: yaml
  datasource:
    init: never
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schema: ${SPRING_DATASOURCE_ACCOUNT_SCHEMA}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: ${SPRING_DATASOURCE_URL}
    enabled: true
    default-schema: ${SPRING_DATASOURCE_ACCOUNT_SCHEMA}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
keycloak:
  server-url: http://keycloak:7080/
  realm: zbank
  username: gatekeeper
  password: swordfish
exceptions:
  makeAccFailure: Не удалось создать счёт
  searchAccFailure: Счёт не найден
  makeUserFailure: Пользователь не создан
  searchUserFailure: Пользователь не найден по имени
  deserFailure: Cannot deserialize payload
  operationFailure: Operation type not recognized
  passEditFailure: Password is not updated
scheduler:
  enabled: true