spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
            user-name-attribute: preferred_username
        registration:
          zbankapi:
            provider: keycloak
            client-id: zbankapi
            client-secret: yBxbVdRbMIgOHjEhDaV8aTp8pYl1UXe1
            authorization-grant-type: client_credentials
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.local/realms/zbank}
          user-name-attribute: preferred_username
  datasource:
    init: never
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schema: ${SPRING_DATASOURCE_ACCOUNT_SCHEMA}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: ${SPRING_DATASOURCE_URL}
    enabled: true
    default-schema: ${SPRING_DATASOURCE_ACCOUNT_SCHEMA}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://keycloak.local/}
  realm: ${KEYCLOAK_SERVER_REALM:zbank}
  username: ${KEYCLOAK_SERVER_USERNAME:gatekeeper}
  password: ${KEYCLOAK_SERVER_PASSWORD:swordfish}
exceptions:
  makeAccFailure: ${EXCEPTIONS_MAKE_ACCFAILURE:Не удалось создать счёт}
  searchAccFailure: ${EXCEPTIONS_SEARCH_ACCFAILURE:Счёт не найден}
  makeUserFailure: ${EXCEPTIONS_MAKE_USERFAILURE:Пользователь не создан}
  searchUserFailure: ${EXCEPTIONS_SEARCH_USERFAILURE:Пользователь не найден по имени}
  deserFailure: ${EXCEPTIONS_DESER_FAILURE:Cannot deserialize payload}
  operationFailure: ${EXCEPTIONS_OPERATION_FAILURE:Operation type not recognized}
  passEditFailure: ${EXCEPTIONS_PASS_EDIT_FAILURE:Password is not updated}
scheduler:
  enabled: ${SCHEDULER_ENABLED:true}
management:
  zipkin:
    tracing:
      endpoint:  http://${spring.release.name:financeapp}-zipkin:9411/api/v2/spans # Эндпоинт Zipkin для приёма спанов
  tracing:
    sampling:
      probability: 1 # Сэмплируем все запросы