apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "front-ui.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ index .Values "serviceAccount" "name" | default (include "front-ui.serviceAccountName" .) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "front-ui.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io