apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "audit-service.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  {{ toYaml .Values.audit-service.rbac.rules | indent 2 }}
  {{- end }}