apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dictionaries-service.fullname" . }}
  labels:
    {{- include "dictionaries-service.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
    # Note: We process database_url separately below using tpl
    {{- range $key, $value := .Values.config }}
    {{- if ne $key "database_url" }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

    # Example: Include other config defined in values.yaml
    # OTHER_CONFIG_PARAM: {{ .Values.config.some_other_config | quote }}